### ISSUE TITLE
Visualization of network tweaking

### ISSUE THREAD

**Issue by joshua-shuhan** [media-comp/2022-CapsuleNetwork#1]
Hi! I am working on an interactive interface for vector tweaking. I am building a Flask app for it.
I want to make sure that I understand the task correctly. The following is my understanding.

1. The interface should take 4 input arguments, `digit`, `dimension`, `lower_bound`, and `upper_bound`.
2. The interface should show 10 figures generated by `tweak_visualize.py`.

And I have some questions about the range of inputs. For example, the `digit` should be an integer from 0 to 9. However, what is the range of other variables?

I really appreciate any help you can provide.

**Comment by shuhuh** [comment]
Sorry I just saw the issue.

The value for `dimension` is an integer between 0 and 15. The function `find_visuals` returns 12 images including the original and 11 reconstructed ones. The `lower_bound` and `upper_bound` are -0.25 and 0.25 by default, which is given by the original paper, and you can basically choose any value you want (maybe not too extreme).

The way I imagine how the interactive interface works is that we have a bar that we can toggle, each point on it represents the tweaked value at the given dimension of the given digit, and then the reconstructed image is shown.

I am unsure how you actually implement an interactive interface, so if you have any other questions please post them.

And if you don't want to train the model, I have the tar file of a trained model that I can send it to you.

(edited: added a new line)
Now I have added the `--interval` option, and you can choose how many reconstructed images you want by it (10 by default, meaning 11 reconstructed images in total).

**Comment by joshua-shuhan** [comment]
Thanks for your response. Got it.

**Comment by joshua-shuhan** [comment]
Hi! Please check my latest implementation.
- An interval input is added.
- A slider bar is added.
- The left hand side figure will change when moving the slider bar.
- The original figure is displayed in the bottom right.

![image](https://user-images.githubusercontent.com/54022159/170431022-fb402c26-b0f4-4c2e-bf01-0f666f64c2da.png)

**Comment by shuhuh** [comment]
This looks absolutely fantastic, please start a pull request and I'll merge it! Thank you!

**Comment by joshua-shuhan** [comment]
Thank you. I made a PR. Please take a look.
